# -*- coding: utf-8 -*-
"""Linear Regression.ripynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19ngq-85odee-9yJet5lL8Udc2_hutupT

# follow up  template after that write the code

## 1. Let's Now Import library of pandas and numpy
"""



"""## 2. Load The Data into a Pandas Frame , hint  use **pd.read_csv**"""



"""## 3. define x is the features of dataframe and y is label , hint use **df.iloc**"""



"""### 4.Drop (id,date) column from x(independent variables ),  hint use **drop()** function"""



"""## 5. Splitting the dataset into the Training set and Test set and put **random_state=2**

"""



"""## 6. Fitting Linear Regression to the dataset and count regression.score"""

